name: Continuous Integration Pull Request

on:
  pull_request:
    branches:
      - 'dev'
      - 'task/**'
      - 'feature/**'
      - 'fix/**'
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review

  workflow_dispatch:

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ci-pr-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ci-pr-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  ci-pr:
    name: PR Linting
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Restore Dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ci-pr-${{ hashFiles('**/package-lock.json') }}

      - name: Lint Pull Request
        run: |
          npm run lint
